package com.htttdn.crm.service;

import com.fasterxml.jackson.databind.JsonNode; import com.htttdn.crm.entity.*; import com.htttdn.crm.exception.ApiException; import com.htttdn.crm.repository.*; import org.springframework.data.domain.*; import org.springframework.http.HttpStatus; import org.springframework.scheduling.annotation.Scheduled; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.time.*; import java.util.*;

@Service
public class OrderService {
    private final OrderRepository orders; private final ProductRepository products; private final CartItemRepository carts; private final PaymentRepository payments; private final PaymentWebhookEventRepository webhookEvents; private final PayosService payos;
    public OrderService(OrderRepository orders,ProductRepository products,CartItemRepository carts,PaymentRepository payments,PaymentWebhookEventRepository webhookEvents,PayosService payos){this.orders=orders;this.products=products;this.carts=carts;this.payments=payments;this.webhookEvents=webhookEvents;this.payos=payos;}
    @Transactional public Checkout create(User customer,CheckoutRequest request){
        if(request.deliveryAddress()==null||request.deliveryAddress().isBlank())throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_CART","Vui lòng nhập địa chỉ giao hàng.");String method=request.paymentMethod()==null?"PAYOS":request.paymentMethod().toUpperCase(Locale.ROOT);if(!Set.of("PAYOS","COD").contains(method))throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_PAYMENT_METHOD","Phương thức thanh toán không hợp lệ.");
        List<RequestedItem> requested=request.items()!=null&&!request.items().isEmpty()?request.items():carts.findByCustomerIdOrderByIdAsc(customer.getId()).stream().map(i->new RequestedItem(i.getProduct().getId(),i.getQuantity(),i.getSize(),i.getColor())).toList();if(requested.isEmpty())throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_CART","Giỏ hàng đang trống.");
        Order order=new Order();order.setCustomer(customer);order.setOrderCode(nextCode());order.setDeliveryAddress(request.deliveryAddress().trim());order.setPaymentMethod(method);order.setCreatedAt(Instant.now());order.setUpdatedAt(Instant.now());order.setStatus("COD".equals(method)?"CONFIRMED":"PENDING_PAYMENT");order.setPaymentStatus("COD".equals(method)?"COD":"PENDING");order.setExpiresAt("COD".equals(method)?null:Instant.now().plus(Duration.ofMinutes(15)));
        BigDecimal total=BigDecimal.ZERO;for(RequestedItem line:requested){if(line==null||line.productId()==null||line.quantity()<1)throw invalidCart();Product p=products.findLockedById(line.productId()).filter(Product::isActive).orElseThrow(()->invalidCart());if(line.quantity()>p.getStock())throw new ApiException(HttpStatus.CONFLICT,"OUT_OF_STOCK","Sản phẩm "+p.getName()+" không đủ số lượng.");p.setStock(p.getStock()-line.quantity());p.setUpdatedAt(Instant.now());products.save(p);OrderItem item=new OrderItem();item.setOrder(order);item.setProduct(p);item.setQuantity(line.quantity());item.setSize(line.size());item.setColor(line.color());item.setUnitPrice(CartService.price(p));order.getItems().add(item);total=total.add(item.getUnitPrice().multiply(BigDecimal.valueOf(item.getQuantity())));}
        order.setTotalAmount(total);orders.save(order);carts.deleteByCustomerId(customer.getId());Payment payment=new Payment();payment.setOrder(order);payment.setAmount(total);payment.setExpiresAt(order.getExpiresAt());if("COD".equals(method)){payment.setStatus("COD");payments.save(payment);return new Checkout(view(order),null,null);}PayosService.Link link=payos.createPaymentLink(order);payment.setPaymentLinkId(link.paymentLinkId());payment.setCheckoutUrl(link.checkoutUrl());payments.save(payment);return new Checkout(view(order),link.checkoutUrl(),link.paymentLinkId());
    }
    @Transactional(readOnly=true) public Page<OrderView> history(User customer,int page,int size){if(page<0||size<1||size>50)throw new ApiException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","Tham số phân trang không hợp lệ.");return orders.findByCustomerIdOrderByCreatedAtDesc(customer.getId(),PageRequest.of(page,size)).map(this::view);}
    @Transactional(readOnly=true) public OrderView detail(User customer,Long id){return view(orders.findByIdAndCustomerId(id,customer.getId()).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"ORDER_NOT_FOUND","Không tìm thấy đơn hàng.")));}
    @Transactional public boolean webhook(JsonNode payload,String signature){JsonNode data=payload==null?null:payload.path("data");if(data==null||data.isMissingNode())throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_WEBHOOK","Webhook không có dữ liệu thanh toán.");if(!payos.verifyWebhook(data,signature))throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_WEBHOOK","Chữ ký webhook không hợp lệ.");long code=data.path("orderCode").asLong(0);String providerCode=data.path("code").asText(payload.path("code").asText(""));boolean success=payload.path("success").asBoolean(false);Order order=orders.findByOrderCode(code).orElseThrow(()->new ApiException(HttpStatus.BAD_REQUEST,"INVALID_WEBHOOK","Không tìm thấy đơn hàng tương ứng."));BigDecimal amount=BigDecimal.valueOf(data.path("amount").asDouble(-1));if(code==0||amount.compareTo(order.getTotalAmount())!=0)throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_WEBHOOK","Thông tin đơn hàng hoặc số tiền không khớp.");String eventKey=data.path("paymentLinkId").asText("")+":"+code+":"+data.path("transactionDateTime").asText("")+":"+providerCode;if(webhookEvents.existsByEventKey(eventKey))return true;PaymentWebhookEvent event=new PaymentWebhookEvent();event.setEventKey(eventKey);event.setOrderCode(code);webhookEvents.save(event);Payment payment=payments.findByOrderId(order.getId()).orElseThrow(()->new ApiException(HttpStatus.BAD_REQUEST,"INVALID_WEBHOOK","Không tìm thấy giao dịch."));if(success&&"00".equals(providerCode)){payment.setStatus("PAID");order.setPaymentStatus("PAID");order.setStatus("CONFIRMED");}else{String desc=data.path("desc").asText("").toLowerCase(Locale.ROOT);payment.setStatus(desc.contains("expire")?"EXPIRED":"CANCELLED");order.setPaymentStatus(payment.getStatus());order.setStatus("CANCELLED");releaseStock(order);}payment.setUpdatedAt(Instant.now());order.setUpdatedAt(Instant.now());payments.save(payment);orders.save(order);return false;}
    @Scheduled(fixedDelayString="${app.payment-cleanup-ms:300000}") @Transactional public void cleanupExpired(){for(Order order:orders.findExpiredPending(Instant.now())){if(!"PENDING_PAYMENT".equals(order.getStatus()))continue;payments.findByOrderId(order.getId()).ifPresent(p->{p.setStatus("EXPIRED");p.setUpdatedAt(Instant.now());payments.save(p);});order.setPaymentStatus("EXPIRED");order.setStatus("CANCELLED");releaseStock(order);order.setUpdatedAt(Instant.now());orders.save(order);}}
    private void releaseStock(Order order){if(order.isStockReleased())return;for(OrderItem item:order.getItems()){products.findById(item.getProduct().getId()).ifPresent(p->{p.setStock(p.getStock()+item.getQuantity());p.setUpdatedAt(Instant.now());products.save(p);});}order.setStockReleased(true);}
    private ApiException invalidCart(){return new ApiException(HttpStatus.BAD_REQUEST,"INVALID_CART","Sản phẩm trong giỏ không còn hợp lệ.");}
    private long nextCode(){long code=100000000000L+(System.currentTimeMillis()%89999999999L);while(orders.findByOrderCode(code).isPresent())code++;return code;}
    public OrderView view(Order o){List<OrderLineView> lines=o.getItems().stream().map(i->new OrderLineView(i.getProduct().getId(),i.getProduct().getName(),i.getProduct().getImageUrl(),i.getQuantity(),i.getUnitPrice(),i.getUnitPrice().multiply(BigDecimal.valueOf(i.getQuantity())),i.getSize(),i.getColor())).toList();return new OrderView(o.getId(),o.getOrderCode(),o.getStatus(),o.getPaymentStatus(),o.getPaymentMethod(),o.getDeliveryAddress(),o.getTotalAmount(),o.getCreatedAt(),o.getUpdatedAt(),lines);}
    public record RequestedItem(Long productId,int quantity,String size,String color){} public record CheckoutRequest(String deliveryAddress,String paymentMethod,List<RequestedItem> items){} public record Checkout(OrderView order,String paymentUrl,String paymentLinkId){} public record OrderView(Long id,Long orderCode,String status,String paymentStatus,String paymentMethod,String deliveryAddress,BigDecimal totalAmount,Instant createdAt,Instant updatedAt,List<OrderLineView> items){} public record OrderLineView(Long productId,String name,String imageUrl,int quantity,BigDecimal unitPrice,BigDecimal lineTotal,String size,String color){}
}
