package com.htttdn.crm.web;

import com.htttdn.crm.domain.*; import com.htttdn.crm.repo.*; import jakarta.transaction.Transactional; import jakarta.validation.Valid; import org.springframework.data.domain.*; import org.springframework.web.bind.annotation.*; import java.math.*; import java.time.*; import java.util.*;

@RestController @RequestMapping("/api/admin")
public class AdminController {
 private final UserRepository users; private final ProductRepository products; private final FeedbackRepository feedback; private final SurveyRepository surveys; private final OrderRepository orders;
 public AdminController(UserRepository u,ProductRepository p,FeedbackRepository f,SurveyRepository s,OrderRepository o){users=u;products=p;feedback=f;surveys=s;orders=o;}
 private Pageable page(int n,int size){return PageRequest.of(Math.max(0,n),Math.min(100,Math.max(1,size)),Sort.by("id").descending());}
 @GetMapping("/users") public Page<User> userList(@RequestParam(defaultValue="") String q,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size){return users.findByRoleAndFullNameContainingIgnoreCaseOrRoleAndEmailContainingIgnoreCase("CUSTOMER",q,"CUSTOMER",q,page(page,size));}
 @GetMapping("/users/{id}") public User user(@PathVariable Long id){return users.findById(id).orElseThrow();}
 @PutMapping("/users/{id}") public User updateUser(@PathVariable Long id,@Valid @RequestBody UserRequest r){User u=user(id);u.setFullName(r.fullName());u.setPhone(r.phone());u.setPreferences(r.preferences());return users.save(u);}
 @PatchMapping("/users/{id}/lock") public User lock(@PathVariable Long id,@RequestBody LockRequest r){User u=user(id);u.setLocked(r.locked());return users.save(u);}
 @GetMapping("/feedback") public Page<Feedback> feedbackList(@RequestParam(required=false)String status,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size){return status==null?feedback.findAll(page(page,size)):feedback.findByStatus(status,page(page,size));}
 @PatchMapping("/feedback/{id}") public Feedback updateFeedback(@PathVariable Long id,@RequestBody FeedbackRequest r){Feedback f=feedback.findById(id).orElseThrow();if(r.status()!=null)f.setStatus(r.status());if(r.adminResponse()!=null)f.setAdminResponse(r.adminResponse());f.setProcessedAt(Instant.now());return feedback.save(f);}
 @GetMapping("/surveys") public Page<Survey> surveyList(@RequestParam(required=false)String status,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size){return status==null?surveys.findAll(page(page,size)):surveys.findByStatus(status,page(page,size));}
 @PostMapping("/surveys") @Transactional public Survey createSurvey(@Valid @RequestBody SurveyRequest r){Survey s=new Survey();s.setTitle(r.title());s.setDescription(r.description());s.setStartsAt(r.startsAt());s.setEndsAt(r.endsAt());for(int i=0;i<r.questions().size();i++){QuestionRequest q=r.questions().get(i);SurveyQuestion x=new SurveyQuestion();x.setSurvey(s);x.setText(q.text());x.setType(q.type());x.setDisplayOrder(i);x.setOptionsJson(q.optionsJson());s.getQuestions().add(x);}return surveys.save(s);}
 @PatchMapping("/surveys/{id}/publish") public Survey publish(@PathVariable Long id,@RequestParam(defaultValue="true")boolean value){Survey s=surveys.findById(id).orElseThrow();s.setStatus(value?"PUBLISHED":"DRAFT");return surveys.save(s);}
 @DeleteMapping("/surveys/{id}") public void deleteSurvey(@PathVariable Long id){if(!surveys.existsById(id))throw new NoSuchElementException("Survey not found");surveys.deleteById(id);}
 @GetMapping("/products") public Page<Product> productList(@RequestParam(defaultValue="")String q,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size){return products.findByNameContainingIgnoreCaseAndActiveTrue(q,page(page,size));}
 @PostMapping("/products") public Product createProduct(@Valid @RequestBody ProductRequest r){Product p=new Product();copy(p,r);return products.save(p);}
 @PutMapping("/products/{id}") public Product updateProduct(@PathVariable Long id,@Valid @RequestBody ProductRequest r){Product p=products.findById(id).orElseThrow();copy(p,r);p.setUpdatedAt(Instant.now());return products.save(p);}
 @DeleteMapping("/products/{id}") public void archiveProduct(@PathVariable Long id){Product p=products.findById(id).orElseThrow();p.setActive(false);products.save(p);}
 @PatchMapping("/products/{id}/stock") public Product stock(@PathVariable Long id,@RequestBody StockRequest r){if(r.quantity()<0)throw new IllegalArgumentException("quantity must be non-negative");Product p=products.findById(id).orElseThrow();p.setStock(r.quantity());p.setUpdatedAt(Instant.now());return products.save(p);}
 private void copy(Product p,ProductRequest r){p.setName(r.name());p.setCategory(r.category());p.setDescription(r.description());p.setPrice(r.price());p.setStock(r.stock());p.setImageUrl(r.imageUrl());}
 @GetMapping("/orders") public Page<Order> orderList(@RequestParam(required=false)String status,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size){return status==null?orders.findAll(page(page,size)):orders.findByStatus(status,page(page,size));}
 @GetMapping("/orders/{id}") public Order order(@PathVariable Long id){return orders.findById(id).orElseThrow();}
 @PatchMapping("/orders/{id}/status") public Order orderStatus(@PathVariable Long id,@RequestBody StatusRequest r){Order o=order(id);if(!Set.of("PENDING_PAYMENT","CONFIRMED","SHIPPED","DELIVERED","COMPLETED","CANCELLED").contains(r.status()))throw new IllegalArgumentException("Invalid order status");o.setStatus(r.status());o.setUpdatedAt(Instant.now());return orders.save(o);}
 @GetMapping("/reports/revenue") public Map<String,Object> revenue(){return Map.of("totalRevenue",Optional.ofNullable(orders.revenue()).orElse(BigDecimal.ZERO),"orders",orders.count());}
 @GetMapping("/reports/users") public Map<String,Object> usersReport(){return Map.of("customers",users.countByRole("CUSTOMER"),"admins",users.countByRole("ADMIN"),"lockedCustomers",users.findAll().stream().filter(User::isLocked).count());}
 @GetMapping("/surveys/stats") public Map<String,Object> surveyStats(){return Map.of("total",surveys.count(),"draft",surveys.countByStatus("DRAFT"),"published",surveys.countByStatus("PUBLISHED"));}
 public record UserRequest(String fullName,String phone,String preferences){} public record LockRequest(boolean locked){} public record FeedbackRequest(String status,String adminResponse){} public record StatusRequest(String status){} public record StockRequest(int quantity){} public record ProductRequest(String name,String category,String description,BigDecimal price,int stock,String imageUrl){} public record QuestionRequest(String text,String type,String optionsJson){} public record SurveyRequest(String title,String description,Instant startsAt,Instant endsAt,List<QuestionRequest> questions) { public SurveyRequest {if(questions==null)questions=List.of();} }
}
