package com.htttdn.crm.controller;

import com.htttdn.crm.entity.*; import com.htttdn.crm.exception.ApiException; import com.htttdn.crm.repository.*; import com.htttdn.crm.service.AuthService; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import java.time.Instant; import java.util.*;

@RestController
public class FeedbackController {
    private final AuthService auth; private final UserRepository users; private final ProductRepository products; private final FeedbackRepository feedback; private final OrderRepository orders;
    public FeedbackController(AuthService auth,UserRepository users,ProductRepository products,FeedbackRepository feedback,OrderRepository orders){this.auth=auth;this.users=users;this.products=products;this.feedback=feedback;this.orders=orders;}
    @GetMapping("/api/products/{productId}/feedback") public List<FeedbackView> list(@PathVariable Long productId){return feedback.findAll().stream().filter(f->f.getProduct()!=null&&f.getProduct().getId().equals(productId)).sorted(Comparator.comparing(Feedback::getCreatedAt).reversed()).map(this::view).toList();}
    @PostMapping("/api/products/{productId}/feedback") public ResponseEntity<FeedbackView> create(@RequestHeader(value="Authorization",required=false) String authorization,@PathVariable Long productId,@Valid @RequestBody FeedbackRequest request){User customer=auth.requireCustomer(authorization);Product product=products.findByIdAndActiveTrue(productId).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"PRODUCT_NOT_FOUND","Không tìm thấy sản phẩm."));if(!orders.existsEligiblePurchase(customer.getId(),productId,Set.of("CONFIRMED","SHIPPED","DELIVERED","COMPLETED")))throw new ApiException(HttpStatus.FORBIDDEN,"PURCHASE_REQUIRED","Bạn cần mua và nhận sản phẩm trước khi đánh giá.");if(feedback.findByCustomerIdAndProductId(customer.getId(),productId).isPresent())throw new ApiException(HttpStatus.CONFLICT,"DUPLICATE_FEEDBACK","Bạn đã gửi đánh giá cho sản phẩm này.");Feedback item=new Feedback();item.setCustomer(customer);item.setProduct(product);item.setRating(request.rating());String content=request.comment()==null?"Đánh giá không kèm bình luận.":request.comment().trim();item.setComment(content.isBlank()?"Đánh giá không kèm bình luận.":content);item.setStatus("NEW");item.setCreatedAt(Instant.now());try{return ResponseEntity.status(HttpStatus.CREATED).body(view(feedback.saveAndFlush(item)));}catch(DataIntegrityViolationException e){throw new ApiException(HttpStatus.CONFLICT,"DUPLICATE_FEEDBACK","Bạn đã gửi đánh giá cho sản phẩm này.");}}
    private FeedbackView view(Feedback f){return new FeedbackView(f.getId(),f.getCustomer().getFullName(),f.getRating(),f.getComment(),f.getCreatedAt());}
    public record FeedbackRequest(@Min(1) @Max(5) int rating,@Size(max=4000) String comment){} public record FeedbackView(Long id,String customerName,int rating,String comment,Instant createdAt){}
}
