package com.htttdn.crm.controller;

import com.htttdn.crm.entity.*; import com.htttdn.crm.exception.ApiException; import com.htttdn.crm.repository.*; import com.htttdn.crm.service.AuthService; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import java.time.*; import java.util.*;

@RestController @RequestMapping("/api/surveys")
public class SurveyController {
    private final SurveyRepository surveys; private final SurveyResponseRepository responses; private final AuthService auth;
    public SurveyController(SurveyRepository surveys,SurveyResponseRepository responses,AuthService auth){this.surveys=surveys;this.responses=responses;this.auth=auth;}
    @GetMapping public List<Survey> active(){Instant now=Instant.now();return surveys.findByStatusOrderByCreatedAtDesc("PUBLISHED").stream().filter(s->available(s,now)).toList();}
    @GetMapping("/{id}") public Survey get(@PathVariable Long id){Survey survey=surveys.findByIdAndStatus(id,"PUBLISHED").orElseThrow(this::unavailable);if(!available(survey,Instant.now()))throw unavailable();return survey;}
    @PostMapping("/{id}/responses") public ResponseEntity<?> respond(@RequestHeader(value="Authorization",required=false) String authorization,@PathVariable Long id,@Valid @RequestBody ResponseRequest request){User customer=auth.requireCustomer(authorization);Survey survey=get(id);if(responses.existsByCustomerIdAndSurveyId(customer.getId(),id))throw new ApiException(HttpStatus.CONFLICT,"DUPLICATE_RESPONSE","Bạn đã hoàn thành khảo sát này.");Map<Long,String> answers=new HashMap<>();if(request.answers()!=null)for(AnswerRequest a:request.answers()){if(a==null||a.questionId()==null||a.value()==null||a.value().isBlank())continue;answers.put(a.questionId(),a.value().trim());}for(SurveyQuestion q:survey.getQuestions())if(q.isRequired()&&!answers.containsKey(q.getId()))throw new ApiException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","Vui lòng trả lời đầy đủ các câu hỏi bắt buộc.");SurveyResponse response=new SurveyResponse();response.setCustomer(customer);response.setSurvey(survey);for(SurveyQuestion q:survey.getQuestions()){if(!answers.containsKey(q.getId()))continue;SurveyAnswer a=new SurveyAnswer();a.setResponse(response);a.setQuestion(q);a.setAnswer(answers.get(q.getId()));response.getAnswers().add(a);}try{responses.saveAndFlush(response);}catch(DataIntegrityViolationException e){throw new ApiException(HttpStatus.CONFLICT,"DUPLICATE_RESPONSE","Bạn đã hoàn thành khảo sát này.");}return ResponseEntity.status(HttpStatus.CREATED).body(Map.of("message","Cảm ơn bạn đã hoàn thành khảo sát.","surveyId",id));}
    private boolean available(Survey s,Instant now){return "PUBLISHED".equals(s.getStatus())&&(s.getStartsAt()==null||!now.isBefore(s.getStartsAt()))&&(s.getEndsAt()==null||now.isBefore(s.getEndsAt()));}
    private ApiException unavailable(){return new ApiException(HttpStatus.NOT_FOUND,"SURVEY_NOT_AVAILABLE","Khảo sát không còn khả dụng.");}
    public record ResponseRequest(List<AnswerRequest> answers){} public record AnswerRequest(@NotNull Long questionId,@Size(max=4000) String value){}
}
