import React, { useEffect, useMemo, useState } from 'react';
import { adminApi, adminEndpoints, adminRefreshSession, adminSignIn, adminSignOut } from './api';

const money = value => new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND', maximumFractionDigits: 0 }).format(Number(value || 0));
const pageData = value => value?.content || [];
const navItems = [['dashboard', 'Tổng quan'], ['users', 'Khách hàng'], ['products', 'Sản phẩm'], ['orders', 'Đơn hàng'], ['feedback', 'Phản hồi'], ['surveys', 'Khảo sát']];

export default function AdminApp() {
  const [path, setPath] = useState(window.location.pathname);
  const [admin, setAdmin] = useState(null);
  const [checking, setChecking] = useState(true);
  const [notice, setNotice] = useState(null);
  const section = path.split('/')[2] || 'dashboard';
  const go = next => { const target = next === 'dashboard' ? '/admin' : `/admin/${next}`; window.history.pushState({}, '', target); setPath(target); };
  const notify = (message, type = 'success') => { setNotice({ message, type }); window.setTimeout(() => setNotice(null), 3500); };

  useEffect(() => { const onPop = () => setPath(window.location.pathname); window.addEventListener('popstate', onPop); adminRefreshSession().then(session => { if (session?.admin) setAdmin(session.admin); }).finally(() => setChecking(false)); return () => window.removeEventListener('popstate', onPop); }, []);
  if (checking) return <div className="admin-loading">Đang kiểm tra phiên quản trị...</div>;
  if (!admin || path === '/admin/login') return <AdminLogin onAuthenticated={session => { setAdmin(session.admin); go('dashboard'); }} onNotice={notify}/>;
  return <div className="admin-shell"><aside className="admin-sidebar"><div className="admin-brand">ANH LỚN <span>ADMIN</span></div><div className="admin-profile"><span>{admin.fullName?.slice(0, 1) || 'A'}</span><div><b>{admin.fullName}</b><small>Quản trị viên</small></div></div><nav>{navItems.map(([key, label]) => <button key={key} className={section === key ? 'active' : ''} onClick={() => go(key)}>{label}</button>)}</nav><button className="admin-logout" onClick={async () => { await adminSignOut(); setAdmin(null); go('login'); }}>Đăng xuất</button></aside><main className="admin-main"><header className="admin-topbar"><div><span className="admin-eyebrow">ANH LỚN SHOP / ADMIN</span><h1>{navItems.find(item => item[0] === section)?.[1] || 'Tổng quan'}</h1></div><a href="/" onClick={event => { event.preventDefault(); window.location.href = '/'; }}>Mở storefront ↗</a></header>{section === 'dashboard' && <Dashboard/>}{section === 'users' && <Users notify={notify}/>} {section === 'products' && <Products notify={notify}/>} {section === 'orders' && <Orders notify={notify}/>} {section === 'feedback' && <Feedback notify={notify}/>} {section === 'surveys' && <Surveys notify={notify}/>}</main>{notice && <div className={`admin-toast ${notice.type}`}>{notice.message}</div>}</div>;
}

function AdminLogin({ onAuthenticated, onNotice }) { const [form, setForm] = useState({ email: 'admin@example.com', password: 'password' }); const [busy, setBusy] = useState(false); const submit = async event => { event.preventDefault(); setBusy(true); try { const session = await adminSignIn(form); onAuthenticated(session); } catch (error) { onNotice(error.message, 'error'); } finally { setBusy(false); } }; return <div className="admin-login"><div className="admin-login-card"><div className="admin-mark">AL<span>ADMIN</span></div><span className="admin-eyebrow">ANH LỚN SHOP / PRIVATE AREA</span><h1>Không gian<br/><i>quản trị.</i></h1><p>Đăng nhập để quản lý cửa hàng và dữ liệu khách hàng.</p><form onSubmit={submit}><label>EMAIL<input type="email" required value={form.email} onChange={event => setForm({ ...form, email: event.target.value })}/></label><label>MẬT KHẨU<input type="password" required value={form.password} onChange={event => setForm({ ...form, password: event.target.value })}/></label><button className="admin-primary" disabled={busy}>{busy ? 'ĐANG ĐĂNG NHẬP...' : 'ĐĂNG NHẬP ADMIN →'}</button></form><small className="admin-dev-note">Tài khoản demo: admin@example.com / password</small><a href="/">← Về storefront</a></div></div>; }

function Dashboard() { const [data, setData] = useState(null); useEffect(() => { Promise.all([adminApi(adminEndpoints.revenue), adminApi(adminEndpoints.userReport), adminApi(adminEndpoints.surveyStats)]).then(([revenue, users, surveys]) => setData({ revenue, users, surveys })).catch(() => null); }, []); if (!data) return <PanelLoading/>; return <div className="admin-content"><div className="admin-stat-grid"><Stat label="Doanh thu" value={money(data.revenue.totalRevenue)}/><Stat label="Đơn hàng" value={data.revenue.orders}/><Stat label="Khách hàng" value={data.users.customers}/><Stat label="Survey đã publish" value={data.surveys.published}/></div><div className="admin-welcome"><span className="admin-eyebrow">QUẢN LÝ TẬP TRUNG</span><h2>Dữ liệu rõ ràng.<br/><i>Quyết định nhanh hơn.</i></h2><p>Chọn một nhóm chức năng ở thanh bên để bắt đầu quản lý cửa hàng.</p></div></div>; }
function Stat({ label, value }) { return <div className="admin-stat"><span>{label}</span><strong>{value}</strong><small>Đang cập nhật từ hệ thống</small></div>; }
function PanelLoading() { return <div className="admin-panel"><p>Đang tải dữ liệu...</p></div>; }
function useAdminList(endpoint) { const [data, setData] = useState(null); const load = () => adminApi(endpoint()).then(setData).catch(() => setData({ content: [] })); useEffect(load, []); return { data, load }; }
function Table({ headers, children }) { return <div className="admin-table-wrap"><table><thead><tr>{headers.map(header => <th key={header}>{header}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }

function Users({ notify }) { const { data, load } = useAdminList(adminEndpoints.users); const update = async user => { try { await adminApi(adminEndpoints.lockUser(user.id), { method: 'PATCH', body: { locked: !user.locked } }); notify('Đã cập nhật trạng thái tài khoản.'); load(); } catch (error) { notify(error.message, 'error'); } }; return <div className="admin-panel"><PanelTitle title="Khách hàng" subtitle="Theo dõi và kiểm soát tài khoản customer."/><Table headers={['Họ tên', 'Email', 'Điện thoại', 'Trạng thái', '']}>{pageData(data).map(user => <tr key={user.id}><td><b>{user.fullName}</b></td><td>{user.email}</td><td>{user.phone || '—'}</td><td><span className={`admin-badge ${user.locked ? 'danger' : 'success'}`}>{user.locked ? 'Đã khóa' : 'Hoạt động'}</span></td><td><button className="admin-action" onClick={() => update(user)}>{user.locked ? 'Mở khóa' : 'Khóa'}</button></td></tr>)}</Table></div>; }

function Products({ notify }) { const { data, load } = useAdminList(adminEndpoints.products); const [form, setForm] = useState({ name: '', category: '', price: '', stock: 0, description: '', imageUrl: '' }); const [editing, setEditing] = useState(null); const save = async event => { event.preventDefault(); try { await adminApi(editing ? adminEndpoints.product(editing) : '/api/admin/products', { method: editing ? 'PUT' : 'POST', body: { ...form, price: Number(form.price), stock: Number(form.stock) } }); setForm({ name: '', category: '', price: '', stock: 0, description: '', imageUrl: '' }); setEditing(null); notify('Đã lưu sản phẩm.'); load(); } catch (error) { notify(error.message, 'error'); } }; const archive = async id => { try { await adminApi(adminEndpoints.product(id), { method: 'DELETE' }); notify('Đã ẩn sản phẩm.'); load(); } catch (error) { notify(error.message, 'error'); } }; return <div className="admin-panel"><PanelTitle title="Sản phẩm" subtitle="Quản lý catalog và tồn kho."/><form className="admin-inline-form" onSubmit={save}><input required placeholder="Tên sản phẩm" value={form.name} onChange={event => setForm({ ...form, name: event.target.value })}/><input required placeholder="Danh mục" value={form.category} onChange={event => setForm({ ...form, category: event.target.value })}/><input required type="number" min="0" placeholder="Giá" value={form.price} onChange={event => setForm({ ...form, price: event.target.value })}/><input required type="number" min="0" placeholder="Tồn kho" value={form.stock} onChange={event => setForm({ ...form, stock: event.target.value })}/><button className="admin-primary">{editing ? 'CẬP NHẬT' : 'THÊM SẢN PHẨM'}</button></form><Table headers={['Sản phẩm', 'Danh mục', 'Giá', 'Tồn kho', '']}>{pageData(data).map(product => <tr key={product.id}><td><b>{product.name}</b></td><td>{product.category || '—'}</td><td>{money(product.salePrice || product.price)}</td><td>{product.stock}</td><td><button className="admin-action" onClick={() => { setEditing(product.id); setForm({ name: product.name, category: product.category || '', price: product.price, stock: product.stock, description: product.description || '', imageUrl: product.imageUrl || '' }); }}>Sửa</button><button className="admin-action danger-text" onClick={() => archive(product.id)}>Ẩn</button></td></tr>)}</Table></div>; }

function Orders({ notify }) { const { data, load } = useAdminList(adminEndpoints.orders); const update = async (id, status) => { try { await adminApi(adminEndpoints.orderStatus(id), { method: 'PATCH', body: { status } }); notify('Đã cập nhật đơn hàng.'); load(); } catch (error) { notify(error.message, 'error'); } }; return <div className="admin-panel"><PanelTitle title="Đơn hàng" subtitle="Theo dõi và cập nhật tiến trình giao hàng."/><Table headers={['Mã đơn', 'Khách hàng', 'Tổng tiền', 'Trạng thái', 'Cập nhật']}>{pageData(data).map(order => <tr key={order.id}><td>#{order.orderCode}</td><td>{order.customer?.fullName || 'Customer'}</td><td>{money(order.totalAmount)}</td><td><span className="admin-badge">{order.status}</span></td><td><select value={order.status} onChange={event => update(order.id, event.target.value)}><option>PENDING_PAYMENT</option><option>CONFIRMED</option><option>SHIPPED</option><option>DELIVERED</option><option>COMPLETED</option><option>CANCELLED</option></select></td></tr>)}</Table></div>; }

function Feedback({ notify }) { const { data, load } = useAdminList(adminEndpoints.feedback); const update = async (item, status) => { try { await adminApi(adminEndpoints.feedbackItem(item.id), { method: 'PATCH', body: { status, adminResponse: item.adminResponse || '' } }); notify('Đã xử lý phản hồi.'); load(); } catch (error) { notify(error.message, 'error'); } }; return <div className="admin-panel"><PanelTitle title="Phản hồi" subtitle="Theo dõi đánh giá và trả lời khách hàng."/><Table headers={['Khách hàng', 'Sản phẩm', 'Đánh giá', 'Nội dung', 'Trạng thái']}>{pageData(data).map(item => <tr key={item.id}><td>{item.customer?.fullName || 'Customer'}</td><td>{item.product?.name || '—'}</td><td>{'★'.repeat(item.rating)}</td><td>{item.comment || '—'}</td><td><select value={item.status || 'NEW'} onChange={event => update(item, event.target.value)}><option>NEW</option><option>IN_PROGRESS</option><option>RESOLVED</option></select></td></tr>)}</Table></div>; }

function Surveys({ notify }) { const { data, load } = useAdminList(adminEndpoints.surveys); const [title, setTitle] = useState(''); const create = async event => { event.preventDefault(); try { await adminApi('/api/admin/surveys', { method: 'POST', body: { title, description: '', questions: [] } }); setTitle(''); notify('Đã tạo khảo sát.'); load(); } catch (error) { notify(error.message, 'error'); } }; const publish = async survey => { try { await adminApi(adminEndpoints.surveyPublish(survey.id), { method: 'PATCH', body: null }); notify('Đã cập nhật survey.'); load(); } catch (error) { notify(error.message, 'error'); } }; const remove = async id => { try { await adminApi(adminEndpoints.survey(id), { method: 'DELETE' }); notify('Đã xóa survey.'); load(); } catch (error) { notify(error.message, 'error'); } }; return <div className="admin-panel"><PanelTitle title="Khảo sát" subtitle="Tạo và phát hành khảo sát phong cách."/><form className="admin-inline-form" onSubmit={create}><input required placeholder="Tên khảo sát mới" value={title} onChange={event => setTitle(event.target.value)}/><button className="admin-primary">TẠO KHẢO SÁT</button></form><Table headers={['Tiêu đề', 'Trạng thái', 'Thao tác']}>{pageData(data).map(survey => <tr key={survey.id}><td><b>{survey.title}</b></td><td><span className="admin-badge">{survey.status}</span></td><td><button className="admin-action" onClick={() => publish(survey)}>{survey.status === 'PUBLISHED' ? 'Gỡ publish' : 'Publish'}</button><button className="admin-action danger-text" onClick={() => remove(survey.id)}>Xóa</button></td></tr>)}</Table></div>; }
function PanelTitle({ title, subtitle }) { return <div className="admin-panel-title"><div><span className="admin-eyebrow">ADMIN MANAGEMENT</span><h2>{title}</h2><p>{subtitle}</p></div></div>; }
